### ISSUE TITLE
[Solved] Make authenticated requests against AppView API?

### ISSUE THREAD

**Issue by marckohlbrugge** [lasercatspro/atproto-ruby#3]
The Javascript libraries allow you to make authenticated API requests to the Bluesky AppView API using just the OAuth tokens. I think they do something behind the scenes to exchange the OAuth tokens for the proper tokens needed for this other API.

Could we add similar support to `atproto-ruby`? Or do you believe it's out-of-scope since I believe it's technically not related to ATProto but to Bluesky.

For example:
```ruby
client.request(:get, "https://bsky.social/xrpc/app.bsky.graph.getFollowers", params: { handle: "marckohlbrugge.com" })
```

Returns the following error:
```ruby
{"error"=>"InvalidToken", "message"=>"OAuth tokens are meant for PDS access only"}
```

**Comment by marckohlbrugge** [comment]
I made some progress. Instead of using `https://bsky.social` (which is what `omniauth-atproto` returns as the PDS host, although it's technically an "Entryway"), we should actually get the actual PDS instance like this:

```ruby
def pds_endpoint
   resolver = DIDKit::Resolver.new
  resolver.resolve_did(did).pds_endpoint
end
```

This returns something like: `"https://porcini.us-east.host.bsky.network"`

Now we can make a request like this:

```ruby
def followers
  client.request(
    :get,
    "#{pds_endpoint}/xrpc/app.bsky.graph.getFollowers",
    params: { actor: "marckohlbrugge.com" }
  )
end
```

This works! Because the PDS actually accepts our OAuth token, unlike `bsky.social`.

The only issue I still run into is that once the access token expires, it no longer works. The client doesn't actually refresh the token for us.

**Comment by marckohlbrugge** [comment]
Should we update the README to clarify the requirement to use the PDS endpoint?

**Comment by frabr** [comment]
I changed the example to be explicit (no more variables), so that people will see what expected urls look like. I also changed the schema to request an endpoint that really needs auth.
